[package]
name = "websnap"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
chrono = "0.4"
md5 = "0.7"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"